name = "vonbusch-soss"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "public", binding = "ASSETS" }

[placement]
mode = "smart"


[[d1_databases]]
binding = "SOSS_DB"
database_name = "vonbusch-soss-eu"
database_id = "e86df9d3-90c7-4fdf-b232-687c70a59f16"

[[d1_databases]]
binding = "CRM_DB"
database_name = "vonbusch-crm-eu"
database_id = "d44390a9-4f6e-4ecc-9193-e8385e98e412"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "vonbusch-crm-docs-eu"
jurisdiction = "eu"

[[r2_buckets]]
binding = "ARCHIVE"
bucket_name = "vonbusch-crm-archiv-eu"
jurisdiction = "eu"

[vars]
APP_URL = "https://soss.vonbusch.app"
MAIL_FROM = "noreply@vonbusch.app"
MAIL_FROM_NAME = "von Busch GmbH"

[observability]

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true
